//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace sqlitemodel {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Sheet1 : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button1;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button2;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label1;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label2;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox tablename;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox db;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnopendb;
        
        internal Microsoft.Office.Tools.Excel.Controls.DataGridView dgvTableDefine;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label3;
        
        internal Microsoft.Office.Tools.Excel.Controls.DataGridView dataGridView1;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label4;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox txtMapType;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnlistMapType;
        
        internal Microsoft.Office.Tools.Excel.Controls.DataGridView dgvMapTypeInfo;
        
        internal System.Windows.Forms.ColumnHeader 序号;
        
        internal System.Windows.Forms.ColumnHeader 字段名;
        
        internal System.Windows.Forms.ColumnHeader 字段类型;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colname;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colDBName;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn coldesc;
        
        internal System.Windows.Forms.DataGridViewComboBoxColumn colDBFieldType;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colMapType;
        
        internal System.Windows.Forms.DataGridViewCheckBoxColumn colindex;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colAvailableMapType;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colOldValue;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colNewValue;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colMapValueDesc;
        
        internal System.Windows.Forms.ColumnHeader 字段说明;
        
        internal System.Windows.Forms.ColumnHeader 数据库字段名;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Sheet1(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet1", "Sheet1") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Sheet1 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.button1 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "12E5D2753176D214A981ADFF19EEDB3A7D3C31", "12E5D2753176D214A981ADFF19EEDB3A7D3C31", this, "button1");
            this.button2 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "203B1A154240DA2435F292A420170CCA3E3062", "203B1A154240DA2435F292A420170CCA3E3062", this, "button2");
            this.label1 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "4CCE9C1324120B44BEA4869A4785E6DAB385B4", "4CCE9C1324120B44BEA4869A4785E6DAB385B4", this, "label1");
            this.label2 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "55693D3E350B8B541DD5AE1D584BD69ED07275", "55693D3E350B8B541DD5AE1D584BD69ED07275", this, "label2");
            this.tablename = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "68A66984E6186464FC76ACEA608C25FA666AF6", "68A66984E6186464FC76ACEA608C25FA666AF6", this, "tablename");
            this.db = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "7E4F9637C75A92742D17B08C75D481466AC7D7", "7E4F9637C75A92742D17B08C75D481466AC7D7", this, "db");
            this.btnopendb = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "865306363851B484EC38B5198B66A220843138", "865306363851B484EC38B5198B66A220843138", this, "btnopendb");
            this.dgvTableDefine = new Microsoft.Office.Tools.Excel.Controls.DataGridView(Globals.Factory, this.ItemProvider, this.HostContext, "109F2244F18E7B1414319747194E7A4F5F6F91", "109F2244F18E7B1414319747194E7A4F5F6F91", this, "dgvTableDefine");
            this.label3 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "1F3989DE313A6514DA8182AF1BB477EC1D5F51", "1F3989DE313A6514DA8182AF1BB477EC1D5F51", this, "label3");
            this.dataGridView1 = new Microsoft.Office.Tools.Excel.Controls.DataGridView(Globals.Factory, this.ItemProvider, this.HostContext, "1A13AFC3717F2E140861A5DF16E927EDA7AB71", "1A13AFC3717F2E140861A5DF16E927EDA7AB71", this, "dataGridView1");
            this.label4 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "10A250F171E9881433D1A8CB16FA083D92D1F1", "10A250F171E9881433D1A8CB16FA083D92D1F1", this, "label4");
            this.txtMapType = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "1F44A06421273614C081A4B112069DF4C576D1", "1F44A06421273614C081A4B112069DF4C576D1", this, "txtMapType");
            this.btnlistMapType = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1BA78A1B91AA2F147F21A2CD17602A966B30E1", "1BA78A1B91AA2F147F21A2CD17602A966B30E1", this, "btnlistMapType");
            this.dgvMapTypeInfo = new Microsoft.Office.Tools.Excel.Controls.DataGridView(Globals.Factory, this.ItemProvider, this.HostContext, "12291BDA114693147B8181BE1BF8193A73D3E1", "12291BDA114693147B8181BE1BF8193A73D3E1", this, "dgvMapTypeInfo");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.colname = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colDBName = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.coldesc = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colDBFieldType = new System.Windows.Forms.DataGridViewComboBoxColumn();
            this.colMapType = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colindex = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.colAvailableMapType = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colOldValue = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colNewValue = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colMapValueDesc = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.序号 = new System.Windows.Forms.ColumnHeader();
            this.字段名 = new System.Windows.Forms.ColumnHeader();
            this.字段类型 = new System.Windows.Forms.ColumnHeader();
            this.字段说明 = new System.Windows.Forms.ColumnHeader();
            this.数据库字段名 = new System.Windows.Forms.ColumnHeader();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTableDefine)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvMapTypeInfo)).BeginInit();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.SystemColors.Control;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Name = "button1";
            this.button1.Text = "创建表";
            this.button1.UseVisualStyleBackColor = false;
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.SystemColors.Control;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Name = "button2";
            this.button2.Text = "打开表";
            this.button2.UseVisualStyleBackColor = false;
            // 
            // label1
            // 
            this.label1.BackColor = System.Drawing.SystemColors.ScrollBar;
            this.label1.Name = "label1";
            this.label1.Text = "数据库设置";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label2
            // 
            this.label2.BackColor = System.Drawing.SystemColors.ScrollBar;
            this.label2.Name = "label2";
            this.label2.Text = "表名";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // tablename
            // 
            this.tablename.Name = "tablename";
            this.tablename.Text = "表名";
            // 
            // db
            // 
            this.db.Name = "db";
            this.db.Text = "数据库";
            // 
            // btnopendb
            // 
            this.btnopendb.BackColor = System.Drawing.SystemColors.Control;
            this.btnopendb.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnopendb.Name = "btnopendb";
            this.btnopendb.Text = "选择数据库";
            this.btnopendb.UseVisualStyleBackColor = false;
            // 
            // dgvTableDefine
            // 
            this.dgvTableDefine.BackgroundColor = System.Drawing.SystemColors.ButtonHighlight;
            this.dgvTableDefine.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
                        this.colname,
                        this.colDBName,
                        this.coldesc,
                        this.colDBFieldType,
                        this.colMapType,
                        this.colindex});
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvTableDefine.DefaultCellStyle = dataGridViewCellStyle1;
            this.dgvTableDefine.GridColor = System.Drawing.SystemColors.ButtonShadow;
            this.dgvTableDefine.Name = "dgvTableDefine";
            this.dgvTableDefine.RowTemplate.Height = 23;
            this.dgvTableDefine.Text = "dataGridView1";
            // 
            // colname
            // 
            this.colname.HeaderText = "字段名称";
            this.colname.Name = "colname";
            this.colname.Width = 200;
            // 
            // colDBName
            // 
            this.colDBName.HeaderText = "字段数据库名称";
            this.colDBName.Name = "colDBName";
            // 
            // coldesc
            // 
            this.coldesc.HeaderText = "字段说明";
            this.coldesc.Name = "coldesc";
            this.coldesc.Width = 200;
            // 
            // colDBFieldType
            // 
            this.colDBFieldType.DisplayStyle = System.Windows.Forms.DataGridViewComboBoxDisplayStyle.ComboBox;
            this.colDBFieldType.HeaderText = "字段数据库类型";
            this.colDBFieldType.Items.AddRange(new object[] {
                        "int",
                        "float",
                        "string"});
            this.colDBFieldType.Name = "colDBFieldType";
            this.colDBFieldType.Resizable = System.Windows.Forms.DataGridViewTriState.True;
            this.colDBFieldType.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
            // 
            // colMapType
            // 
            this.colMapType.HeaderText = "字段映射类型";
            this.colMapType.Name = "colMapType";
            this.colMapType.Width = 200;
            // 
            // colindex
            // 
            this.colindex.HeaderText = "创建索引";
            this.colindex.Name = "colindex";
            // 
            // label3
            // 
            this.label3.Font = new System.Drawing.Font("宋体", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.label3.Name = "label3";
            this.label3.Text = "当前可用映射类型";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // dataGridView1
            // 
            this.dataGridView1.BackgroundColor = System.Drawing.SystemColors.ButtonHighlight;
            this.dataGridView1.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
                        this.colAvailableMapType});
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridView1.DefaultCellStyle = dataGridViewCellStyle2;
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.RowTemplate.Height = 23;
            this.dataGridView1.Text = "dataGridView1";
            // 
            // colAvailableMapType
            // 
            this.colAvailableMapType.HeaderText = "当前可用的映射类型";
            this.colAvailableMapType.Name = "colAvailableMapType";
            this.colAvailableMapType.Width = 200;
            // 
            // label4
            // 
            this.label4.Font = new System.Drawing.Font("宋体", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.label4.Name = "label4";
            this.label4.Text = "查看映射类型";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // txtMapType
            // 
            this.txtMapType.Font = new System.Drawing.Font("宋体", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.txtMapType.Name = "txtMapType";
            this.txtMapType.Text = "textBox1";
            // 
            // btnlistMapType
            // 
            this.btnlistMapType.BackColor = System.Drawing.SystemColors.Control;
            this.btnlistMapType.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnlistMapType.Name = "btnlistMapType";
            this.btnlistMapType.Text = "列出映射类型的值";
            this.btnlistMapType.UseVisualStyleBackColor = false;
            // 
            // dgvMapTypeInfo
            // 
            this.dgvMapTypeInfo.BackgroundColor = System.Drawing.SystemColors.ButtonHighlight;
            this.dgvMapTypeInfo.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
                        this.colOldValue,
                        this.colNewValue,
                        this.colMapValueDesc});
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvMapTypeInfo.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvMapTypeInfo.Name = "dgvMapTypeInfo";
            this.dgvMapTypeInfo.RowTemplate.Height = 23;
            this.dgvMapTypeInfo.Text = "dataGridView2";
            // 
            // colOldValue
            // 
            this.colOldValue.HeaderText = "原始值";
            this.colOldValue.Name = "colOldValue";
            this.colOldValue.Width = 150;
            // 
            // colNewValue
            // 
            this.colNewValue.HeaderText = "映射值";
            this.colNewValue.Name = "colNewValue";
            this.colNewValue.Width = 200;
            // 
            // colMapValueDesc
            // 
            this.colMapValueDesc.HeaderText = "映射说明";
            this.colMapValueDesc.Name = "colMapValueDesc";
            this.colMapValueDesc.Width = 200;
            // 
            // Sheet1
            // 
            ((System.ComponentModel.ISupportInitialize)(this.dgvTableDefine)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvMapTypeInfo)).EndInit();
            this.button1.BindingContext = this.BindingContext;
            this.button2.BindingContext = this.BindingContext;
            this.label1.BindingContext = this.BindingContext;
            this.label2.BindingContext = this.BindingContext;
            this.tablename.BindingContext = this.BindingContext;
            this.db.BindingContext = this.BindingContext;
            this.btnopendb.BindingContext = this.BindingContext;
            this.dgvTableDefine.BindingContext = this.BindingContext;
            this.label3.BindingContext = this.BindingContext;
            this.dataGridView1.BindingContext = this.BindingContext;
            this.label4.BindingContext = this.BindingContext;
            this.txtMapType.BindingContext = this.BindingContext;
            this.btnlistMapType.BindingContext = this.BindingContext;
            this.dgvMapTypeInfo.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
    }
    
    internal sealed partial class Globals {
        
        private static Sheet1 _Sheet1;
        
        internal static Sheet1 Sheet1 {
            get {
                return _Sheet1;
            }
            set {
                if ((_Sheet1 == null)) {
                    _Sheet1 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
