//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace sqlitemodel {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Sheet1 : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnCreate;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnOpen;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label1;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label2;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox db;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnopendb;
        
        internal Microsoft.Office.Tools.Excel.Controls.DataGridView dgvTableDefine;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label3;
        
        internal Microsoft.Office.Tools.Excel.Controls.DataGridView dgvAvailableMapType;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label4;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox txtMapType;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnlistMapType;
        
        internal Microsoft.Office.Tools.Excel.Controls.DataGridView dgvMapTypeInfo;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnCreateDB;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox cboTable;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label5;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox txtNewTableName;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnstartCreate;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label6;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox txtTableDBName;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox cboavailabletemplelate;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnselect;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btndeletetable;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox cboToModifyTable;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox txtmoname;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox txtmodbname;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label yuan;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label8;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label9;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label10;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox txtmonewname;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox txtmonewdbname;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnmodify;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnRelease;
        
        internal System.Windows.Forms.ColumnHeader 序号;
        
        internal System.Windows.Forms.ColumnHeader 字段名;
        
        internal System.Windows.Forms.ColumnHeader 字段类型;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colAvailableMapType;
        
        internal System.Windows.Forms.ColumnHeader 字段说明;
        
        internal System.Windows.Forms.ColumnHeader 数据库字段名;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colname;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colDBName;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn coldesc;
        
        internal System.Windows.Forms.DataGridViewComboBoxColumn colDBFieldType;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colMapType;
        
        internal System.Windows.Forms.DataGridViewCheckBoxColumn colindex;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colRecordOrder;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colOldValue;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colNewValue;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn colMapValueDesc;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn1;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Sheet1(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet1", "Sheet1") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Sheet1 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.btnCreate = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "12E5D2753176D214A981ADFF19EEDB3A7D3C31", "12E5D2753176D214A981ADFF19EEDB3A7D3C31", this, "btnCreate");
            this.btnOpen = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "203B1A154240DA2435F292A420170CCA3E3062", "203B1A154240DA2435F292A420170CCA3E3062", this, "btnOpen");
            this.label1 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "4CCE9C1324120B44BEA4869A4785E6DAB385B4", "4CCE9C1324120B44BEA4869A4785E6DAB385B4", this, "label1");
            this.label2 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "55693D3E350B8B541DD5AE1D584BD69ED07275", "55693D3E350B8B541DD5AE1D584BD69ED07275", this, "label2");
            this.db = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "7E4F9637C75A92742D17B08C75D481466AC7D7", "7E4F9637C75A92742D17B08C75D481466AC7D7", this, "db");
            this.btnopendb = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "865306363851B484EC38B5198B66A220843138", "865306363851B484EC38B5198B66A220843138", this, "btnopendb");
            this.dgvTableDefine = new Microsoft.Office.Tools.Excel.Controls.DataGridView(Globals.Factory, this.ItemProvider, this.HostContext, "109F2244F18E7B1414319747194E7A4F5F6F91", "109F2244F18E7B1414319747194E7A4F5F6F91", this, "dgvTableDefine");
            this.label3 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "1F3989DE313A6514DA8182AF1BB477EC1D5F51", "1F3989DE313A6514DA8182AF1BB477EC1D5F51", this, "label3");
            this.dgvAvailableMapType = new Microsoft.Office.Tools.Excel.Controls.DataGridView(Globals.Factory, this.ItemProvider, this.HostContext, "1A13AFC3717F2E140861A5DF16E927EDA7AB71", "1A13AFC3717F2E140861A5DF16E927EDA7AB71", this, "dgvAvailableMapType");
            this.label4 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "10A250F171E9881433D1A8CB16FA083D92D1F1", "10A250F171E9881433D1A8CB16FA083D92D1F1", this, "label4");
            this.txtMapType = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "1F44A06421273614C081A4B112069DF4C576D1", "1F44A06421273614C081A4B112069DF4C576D1", this, "txtMapType");
            this.btnlistMapType = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1BA78A1B91AA2F147F21A2CD17602A966B30E1", "1BA78A1B91AA2F147F21A2CD17602A966B30E1", this, "btnlistMapType");
            this.dgvMapTypeInfo = new Microsoft.Office.Tools.Excel.Controls.DataGridView(Globals.Factory, this.ItemProvider, this.HostContext, "12291BDA114693147B8181BE1BF8193A73D3E1", "12291BDA114693147B8181BE1BF8193A73D3E1", this, "dgvMapTypeInfo");
            this.btnCreateDB = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1AFB2B17B1E98C1439E1B6C81B311B185DD461", "1AFB2B17B1E98C1439E1B6C81B311B185DD461", this, "btnCreateDB");
            this.cboTable = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "16E251DBE1D2A0140141BC0D1C183BDB3A4021", "16E251DBE1D2A0140141BC0D1C183BDB3A4021", this, "cboTable");
            this.label5 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "133ADD7A7152C514B08193DF1F9EA7A4EB19D1", "133ADD7A7152C514B08193DF1F9EA7A4EB19D1", this, "label5");
            this.txtNewTableName = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "20218A97D22EDF24EBA2BD402C17A21D46EF02", "20218A97D22EDF24EBA2BD402C17A21D46EF02", this, "txtNewTableName");
            this.btnstartCreate = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "2C226BA75293532414E294EF2E8FFD852516E2", "2C226BA75293532414E294EF2E8FFD852516E2", this, "btnstartCreate");
            this.label6 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "24FD265452D60024F9A280F02550102B3AD382", "24FD265452D60024F9A280F02550102B3AD382", this, "label6");
            this.txtTableDBName = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "23625AFFA2628524BD1294142C1CE98943D5C2", "23625AFFA2628524BD1294142C1CE98943D5C2", this, "txtTableDBName");
            this.cboavailabletemplelate = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "323607CF7350DE340A8388243C57AAF0EAC1F3", "323607CF7350DE340A8388243C57AAF0EAC1F3", this, "cboavailabletemplelate");
            this.btnselect = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "35D3B845434FBE3434F3846130EB347A64B2E3", "35D3B845434FBE3434F3846130EB347A64B2E3", this, "btnselect");
            this.btndeletetable = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "3318E66D2387FF34F333A22D3C94A688FEC693", "3318E66D2387FF34F333A22D3C94A688FEC693", this, "btndeletetable");
            this.cboToModifyTable = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "3115F63EB30C51347463847B35CFFBE28EF763", "3115F63EB30C51347463847B35CFFBE28EF763", this, "cboToModifyTable");
            this.txtmoname = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "3F83E0BD3350E834E843B8813B985FC503EB53", "3F83E0BD3350E834E843B8813B985FC503EB53", this, "txtmoname");
            this.txtmodbname = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "3648C574D3F34934C3A394EF3DB95740107D83", "3648C574D3F34934C3A394EF3DB95740107D83", this, "txtmodbname");
            this.yuan = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "32E44DD8A3151034DF738B1E375C505F44B323", "32E44DD8A3151034DF738B1E375C505F44B323", this, "yuan");
            this.label8 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "3CD83B4A7328303423A39AFE36684931983D63", "3CD83B4A7328303423A39AFE36684931983D63", this, "label8");
            this.label9 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "3A76453313A8703422A3816336AA84B7B3FDE3", "3A76453313A8703422A3816336AA84B7B3FDE3", this, "label9");
            this.label10 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "4A898DCB94658D4453748A584FFE944C456B14", "4A898DCB94658D4453748A584FFE944C456B14", this, "label10");
            this.txtmonewname = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "44DA5B41A42BE54477449E9040850944343DA4", "44DA5B41A42BE54477449E9040850944343DA4", this, "txtmonewname");
            this.txtmonewdbname = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "4C67F8248414ED4403B4A0574FF5CBD5D33894", "4C67F8248414ED4403B4A0574FF5CBD5D33894", this, "txtmonewdbname");
            this.btnmodify = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "48F1B7E4D44859445AE4B0544474117990B964", "48F1B7E4D44859445AE4B0544474117990B964", this, "btnmodify");
            this.btnRelease = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "426D876544EF14448B4497B94CEAE6655767F4", "426D876544EF14448B4497B94CEAE6655767F4", this, "btnRelease");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.colname = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colDBName = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.coldesc = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colDBFieldType = new System.Windows.Forms.DataGridViewComboBoxColumn();
            this.colMapType = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colindex = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.colRecordOrder = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colAvailableMapType = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colOldValue = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colNewValue = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colMapValueDesc = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.序号 = new System.Windows.Forms.ColumnHeader();
            this.字段名 = new System.Windows.Forms.ColumnHeader();
            this.字段类型 = new System.Windows.Forms.ColumnHeader();
            this.字段说明 = new System.Windows.Forms.ColumnHeader();
            this.数据库字段名 = new System.Windows.Forms.ColumnHeader();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTableDefine)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvAvailableMapType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvMapTypeInfo)).BeginInit();
            // 
            // btnCreate
            // 
            this.btnCreate.BackColor = System.Drawing.SystemColors.Control;
            this.btnCreate.Enabled = false;
            this.btnCreate.Font = new System.Drawing.Font("宋体", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.btnCreate.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnCreate.Name = "btnCreate";
            this.btnCreate.Text = "保存表";
            this.btnCreate.UseVisualStyleBackColor = false;
            // 
            // btnOpen
            // 
            this.btnOpen.BackColor = System.Drawing.SystemColors.Control;
            this.btnOpen.Enabled = false;
            this.btnOpen.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnOpen.Name = "btnOpen";
            this.btnOpen.Text = "打开表";
            this.btnOpen.UseVisualStyleBackColor = false;
            // 
            // label1
            // 
            this.label1.BackColor = System.Drawing.SystemColors.ScrollBar;
            this.label1.Name = "label1";
            this.label1.Text = "当前数据库";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label2
            // 
            this.label2.BackColor = System.Drawing.SystemColors.ScrollBar;
            this.label2.Name = "label2";
            this.label2.Text = "已有数据表";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // db
            // 
            this.db.Name = "db";
            this.db.Text = "数据库";
            // 
            // btnopendb
            // 
            this.btnopendb.BackColor = System.Drawing.SystemColors.Control;
            this.btnopendb.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnopendb.Name = "btnopendb";
            this.btnopendb.Text = "打开数据库";
            this.btnopendb.UseVisualStyleBackColor = false;
            // 
            // dgvTableDefine
            // 
            this.dgvTableDefine.BackgroundColor = System.Drawing.SystemColors.ButtonHighlight;
            this.dgvTableDefine.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
                        this.colname,
                        this.colDBName,
                        this.coldesc,
                        this.colDBFieldType,
                        this.colMapType,
                        this.colindex,
                        this.colRecordOrder});
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvTableDefine.DefaultCellStyle = dataGridViewCellStyle1;
            this.dgvTableDefine.GridColor = System.Drawing.SystemColors.ButtonShadow;
            this.dgvTableDefine.Name = "dgvTableDefine";
            this.dgvTableDefine.ReadOnly = true;
            this.dgvTableDefine.RowTemplate.Height = 23;
            this.dgvTableDefine.Text = "dataGridView1";
            // 
            // colname
            // 
            this.colname.HeaderText = "字段名称";
            this.colname.Name = "colname";
            this.colname.ReadOnly = true;
            this.colname.Width = 200;
            // 
            // colDBName
            // 
            this.colDBName.HeaderText = "字段数据库名称";
            this.colDBName.Name = "colDBName";
            this.colDBName.ReadOnly = true;
            // 
            // coldesc
            // 
            this.coldesc.HeaderText = "字段说明";
            this.coldesc.Name = "coldesc";
            this.coldesc.ReadOnly = true;
            this.coldesc.Width = 200;
            // 
            // colDBFieldType
            // 
            this.colDBFieldType.DisplayStyle = System.Windows.Forms.DataGridViewComboBoxDisplayStyle.ComboBox;
            this.colDBFieldType.HeaderText = "字段数据库类型";
            this.colDBFieldType.Items.AddRange(new object[] {
                        "integer",
                        "float",
                        "bigint",
                        "varchar(20)",
                        "varchar(10)",
                        "varchar(100)",
                        "varchar(50)",
                        "tinyint",
                        "smallint",
                        "char"});
            this.colDBFieldType.Name = "colDBFieldType";
            this.colDBFieldType.ReadOnly = true;
            this.colDBFieldType.Resizable = System.Windows.Forms.DataGridViewTriState.True;
            this.colDBFieldType.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
            // 
            // colMapType
            // 
            this.colMapType.HeaderText = "字段映射类型";
            this.colMapType.Name = "colMapType";
            this.colMapType.ReadOnly = true;
            this.colMapType.Width = 200;
            // 
            // colindex
            // 
            this.colindex.HeaderText = "创建索引";
            this.colindex.Name = "colindex";
            this.colindex.ReadOnly = true;
            // 
            // colRecordOrder
            // 
            this.colRecordOrder.HeaderText = "字段序号";
            this.colRecordOrder.Name = "colRecordOrder";
            this.colRecordOrder.ReadOnly = true;
            // 
            // label3
            // 
            this.label3.Font = new System.Drawing.Font("宋体", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.label3.Name = "label3";
            this.label3.Text = "当前可用映射类型";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // dgvAvailableMapType
            // 
            this.dgvAvailableMapType.BackgroundColor = System.Drawing.SystemColors.ButtonHighlight;
            this.dgvAvailableMapType.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
                        this.colAvailableMapType});
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvAvailableMapType.DefaultCellStyle = dataGridViewCellStyle2;
            this.dgvAvailableMapType.Name = "dgvAvailableMapType";
            this.dgvAvailableMapType.ReadOnly = true;
            this.dgvAvailableMapType.RowTemplate.Height = 23;
            this.dgvAvailableMapType.Text = "dataGridView1";
            // 
            // colAvailableMapType
            // 
            this.colAvailableMapType.HeaderText = "当前可用的映射类型";
            this.colAvailableMapType.Name = "colAvailableMapType";
            this.colAvailableMapType.ReadOnly = true;
            this.colAvailableMapType.Width = 200;
            // 
            // label4
            // 
            this.label4.Font = new System.Drawing.Font("宋体", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.label4.Name = "label4";
            this.label4.Text = "查看映射类型";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // txtMapType
            // 
            this.txtMapType.Font = new System.Drawing.Font("宋体", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.txtMapType.Name = "txtMapType";
            this.txtMapType.Text = "textBox1";
            // 
            // btnlistMapType
            // 
            this.btnlistMapType.BackColor = System.Drawing.SystemColors.Control;
            this.btnlistMapType.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnlistMapType.Name = "btnlistMapType";
            this.btnlistMapType.Text = "列出映射类型的值";
            this.btnlistMapType.UseVisualStyleBackColor = false;
            // 
            // dgvMapTypeInfo
            // 
            this.dgvMapTypeInfo.BackgroundColor = System.Drawing.SystemColors.ButtonHighlight;
            this.dgvMapTypeInfo.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
                        this.colOldValue,
                        this.colNewValue,
                        this.colMapValueDesc,
                        this.dataGridViewTextBoxColumn1});
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvMapTypeInfo.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvMapTypeInfo.Name = "dgvMapTypeInfo";
            this.dgvMapTypeInfo.ReadOnly = true;
            this.dgvMapTypeInfo.RowTemplate.Height = 23;
            this.dgvMapTypeInfo.Text = "dataGridView2";
            // 
            // colOldValue
            // 
            this.colOldValue.HeaderText = "原始值";
            this.colOldValue.Name = "colOldValue";
            this.colOldValue.ReadOnly = true;
            this.colOldValue.Width = 150;
            // 
            // colNewValue
            // 
            this.colNewValue.HeaderText = "映射值";
            this.colNewValue.Name = "colNewValue";
            this.colNewValue.ReadOnly = true;
            this.colNewValue.Width = 200;
            // 
            // colMapValueDesc
            // 
            this.colMapValueDesc.HeaderText = "映射说明";
            this.colMapValueDesc.Name = "colMapValueDesc";
            this.colMapValueDesc.ReadOnly = true;
            this.colMapValueDesc.Width = 200;
            // 
            // dataGridViewTextBoxColumn1
            // 
            this.dataGridViewTextBoxColumn1.HeaderText = "记录序号";
            this.dataGridViewTextBoxColumn1.Name = "dataGridViewTextBoxColumn1";
            this.dataGridViewTextBoxColumn1.ReadOnly = true;
            // 
            // btnCreateDB
            // 
            this.btnCreateDB.BackColor = System.Drawing.SystemColors.Control;
            this.btnCreateDB.Font = new System.Drawing.Font("宋体", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.btnCreateDB.ForeColor = System.Drawing.Color.Maroon;
            this.btnCreateDB.Name = "btnCreateDB";
            this.btnCreateDB.Text = "没有数据库时，点击创建数据库，有数据库时，在下面打开";
            this.btnCreateDB.UseVisualStyleBackColor = false;
            // 
            // cboTable
            // 
            this.cboTable.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTable.Name = "cboTable";
            // 
            // label5
            // 
            this.label5.BackColor = System.Drawing.SystemColors.ScrollBar;
            this.label5.Name = "label5";
            this.label5.Text = "新表名";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // txtNewTableName
            // 
            this.txtNewTableName.Enabled = false;
            this.txtNewTableName.Font = new System.Drawing.Font("宋体", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.txtNewTableName.Name = "txtNewTableName";
            this.txtNewTableName.Text = "输入新表名";
            // 
            // btnstartCreate
            // 
            this.btnstartCreate.BackColor = System.Drawing.SystemColors.Control;
            this.btnstartCreate.Enabled = false;
            this.btnstartCreate.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnstartCreate.Name = "btnstartCreate";
            this.btnstartCreate.Text = "开始建表";
            this.btnstartCreate.UseVisualStyleBackColor = false;
            // 
            // label6
            // 
            this.label6.BackColor = System.Drawing.SystemColors.ScrollBar;
            this.label6.Name = "label6";
            this.label6.Text = "表数据库名称";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // txtTableDBName
            // 
            this.txtTableDBName.Enabled = false;
            this.txtTableDBName.Font = new System.Drawing.Font("宋体", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.txtTableDBName.Name = "txtTableDBName";
            this.txtTableDBName.Text = "表英文名称";
            // 
            // cboavailabletemplelate
            // 
            this.cboavailabletemplelate.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboavailabletemplelate.Enabled = false;
            this.cboavailabletemplelate.Font = new System.Drawing.Font("宋体", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.cboavailabletemplelate.Name = "cboavailabletemplelate";
            // 
            // btnselect
            // 
            this.btnselect.BackColor = System.Drawing.SystemColors.Control;
            this.btnselect.Enabled = false;
            this.btnselect.Font = new System.Drawing.Font("宋体", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.btnselect.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnselect.Name = "btnselect";
            this.btnselect.Text = "选择模板";
            this.btnselect.UseVisualStyleBackColor = false;
            // 
            // btndeletetable
            // 
            this.btndeletetable.BackColor = System.Drawing.SystemColors.Control;
            this.btndeletetable.Enabled = false;
            this.btndeletetable.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btndeletetable.Name = "btndeletetable";
            this.btndeletetable.Text = "删除表";
            this.btndeletetable.UseVisualStyleBackColor = false;
            // 
            // cboToModifyTable
            // 
            this.cboToModifyTable.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboToModifyTable.Font = new System.Drawing.Font("宋体", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.cboToModifyTable.Name = "cboToModifyTable";
            // 
            // txtmoname
            // 
            this.txtmoname.Enabled = false;
            this.txtmoname.Font = new System.Drawing.Font("宋体", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.txtmoname.Name = "txtmoname";
            // 
            // txtmodbname
            // 
            this.txtmodbname.Enabled = false;
            this.txtmodbname.Font = new System.Drawing.Font("宋体", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.txtmodbname.Name = "txtmodbname";
            // 
            // yuan
            // 
            this.yuan.Name = "yuan";
            this.yuan.Text = "原表名";
            // 
            // label8
            // 
            this.label8.Name = "label8";
            this.label8.Text = "原数据库表名";
            // 
            // label9
            // 
            this.label9.Name = "label9";
            this.label9.Text = "新表名";
            // 
            // label10
            // 
            this.label10.Name = "label10";
            this.label10.Text = "新数据库表名";
            // 
            // txtmonewname
            // 
            this.txtmonewname.Font = new System.Drawing.Font("宋体", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.txtmonewname.Name = "txtmonewname";
            // 
            // txtmonewdbname
            // 
            this.txtmonewdbname.Font = new System.Drawing.Font("宋体", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.txtmonewdbname.Name = "txtmonewdbname";
            // 
            // btnmodify
            // 
            this.btnmodify.BackColor = System.Drawing.SystemColors.Control;
            this.btnmodify.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnmodify.Name = "btnmodify";
            this.btnmodify.Text = "确认修改表名";
            this.btnmodify.UseVisualStyleBackColor = false;
            // 
            // btnRelease
            // 
            this.btnRelease.BackColor = System.Drawing.SystemColors.Control;
            this.btnRelease.Font = new System.Drawing.Font("宋体", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.btnRelease.ForeColor = System.Drawing.Color.Red;
            this.btnRelease.Name = "btnRelease";
            this.btnRelease.Text = "发布数据库";
            this.btnRelease.UseVisualStyleBackColor = false;
            // 
            // Sheet1
            // 
            ((System.ComponentModel.ISupportInitialize)(this.dgvTableDefine)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvAvailableMapType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvMapTypeInfo)).EndInit();
            this.btnCreate.BindingContext = this.BindingContext;
            this.btnOpen.BindingContext = this.BindingContext;
            this.label1.BindingContext = this.BindingContext;
            this.label2.BindingContext = this.BindingContext;
            this.db.BindingContext = this.BindingContext;
            this.btnopendb.BindingContext = this.BindingContext;
            this.dgvTableDefine.BindingContext = this.BindingContext;
            this.label3.BindingContext = this.BindingContext;
            this.dgvAvailableMapType.BindingContext = this.BindingContext;
            this.label4.BindingContext = this.BindingContext;
            this.txtMapType.BindingContext = this.BindingContext;
            this.btnlistMapType.BindingContext = this.BindingContext;
            this.dgvMapTypeInfo.BindingContext = this.BindingContext;
            this.btnCreateDB.BindingContext = this.BindingContext;
            this.cboTable.BindingContext = this.BindingContext;
            this.label5.BindingContext = this.BindingContext;
            this.txtNewTableName.BindingContext = this.BindingContext;
            this.btnstartCreate.BindingContext = this.BindingContext;
            this.label6.BindingContext = this.BindingContext;
            this.txtTableDBName.BindingContext = this.BindingContext;
            this.cboavailabletemplelate.BindingContext = this.BindingContext;
            this.btnselect.BindingContext = this.BindingContext;
            this.btndeletetable.BindingContext = this.BindingContext;
            this.cboToModifyTable.BindingContext = this.BindingContext;
            this.txtmoname.BindingContext = this.BindingContext;
            this.txtmodbname.BindingContext = this.BindingContext;
            this.yuan.BindingContext = this.BindingContext;
            this.label8.BindingContext = this.BindingContext;
            this.label9.BindingContext = this.BindingContext;
            this.label10.BindingContext = this.BindingContext;
            this.txtmonewname.BindingContext = this.BindingContext;
            this.txtmonewdbname.BindingContext = this.BindingContext;
            this.btnmodify.BindingContext = this.BindingContext;
            this.btnRelease.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
    }
    
    internal sealed partial class Globals {
        
        private static Sheet1 _Sheet1;
        
        internal static Sheet1 Sheet1 {
            get {
                return _Sheet1;
            }
            set {
                if ((_Sheet1 == null)) {
                    _Sheet1 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
